from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import Optional, List
from datetime import datetime

from core.database import get_db
from models.env_stack import EnvStack
from models.user import User
from core.security import get_admin_user, get_current_user, TokenUser
from core.config import settings
from core.ssh_executor import SSHExecutor

router = APIRouter()

# ---------------------------------------------------------------------------
# Pre-seeded stacks — created from real modules seen in a standard Spack
# AlmaLinux9 x86_64 install (cmake, hwloc, gcc, python, openmpi are confirmed).
# ---------------------------------------------------------------------------
DEFAULT_STACKS = [
    {
        "name": "base-developer",
        "display_name": "Base Developer Toolchain",
        "description": "Core build tools: GCC compiler, CMake build system, and hardware locality library. The starting point for any compilation task.",
        "category": "Developer",
        "modules": "gcc/11.5.0-xwcconl,cmake/4.3.2,hwloc/2.13.0",
    },
    {
        "name": "core-scripting",
        "display_name": "Python & Perl Scripting",
        "description": "Core runtime environments for Python and Perl scripting, database interactions via SQLite, and utilities like JQ.",
        "category": "Scientific",
        "modules": "python/3.14.5-lddvwjv,perl/5.42.0-dadruwd,sqlite/3.53.1-mfudwzt,jq/1.8.1-jnxci33",
    },
    {
        "name": "data-utilities",
        "display_name": "Compression & System Utilities",
        "description": "Standard file packaging, compression libraries (Zlib, Zstd, XZ), and system monitoring tools like HTOP.",
        "category": "Custom",
        "modules": "htop/3.4.1-wpph7cx,zlib/1.3.2-ycpxie7,zstd/1.5.7-okdgpph,tar/1.35-yjcpajg",
    },
]

# ---------------------------------------------------------------------------
# Pydantic Schemas
# ---------------------------------------------------------------------------

class EnvStackCreate(BaseModel):
    name: str
    display_name: str
    description: Optional[str] = ""
    category: str = "Custom"
    modules: List[str]  # e.g. ["gcc/11.2.0", "cmake"]

class EnvStackUpdate(BaseModel):
    display_name: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    modules: Optional[List[str]] = None

class EnvStackResponse(BaseModel):
    id: int
    name: str
    display_name: str
    description: Optional[str]
    category: str
    modules: List[str]
    created_at: Optional[datetime]

    class Config:
        from_attributes = True

class UserEnvProfileUpdate(BaseModel):
    stack_name: str  # e.g. "base-developer" or "" to reset to base spack

# ---------------------------------------------------------------------------
# Helper: generate Lua metamodule content
# ---------------------------------------------------------------------------

def _build_lua_content(stack: EnvStack) -> str:
    module_list = [m.strip() for m in stack.modules.split(",") if m.strip()]
    load_lines = "\n".join(f'load("{m}")' for m in module_list)
    return f'''-- Auto-generated by HPC Cluster Management System
-- Stack: {stack.display_name} ({stack.name})
-- Category: {stack.category}

help([[{stack.description or stack.display_name}]])
whatis("Version: 1.0")
whatis("Category: {stack.category}")
whatis("Description: {stack.description or stack.display_name}")

-- Load constituent modules
{load_lines}
'''

# ---------------------------------------------------------------------------
# Helper: sentinel-safe bashrc injection
# ---------------------------------------------------------------------------

SENTINEL_START = "# --- HPC PROFILE MANAGED BLOCK START ---"
SENTINEL_END   = "# --- HPC PROFILE MANAGED BLOCK END ---"

def _build_bashrc_block(stack_name: str) -> str:
    """Generates the managed block content for ~/.bashrc"""
    return f"""{SENTINEL_START}
# Source Spack/Lmod setup for non-interactive shells (like Slurm jobs)
if [ -f /etc/profile.d/spack_setup.sh ]; then
    source /etc/profile.d/spack_setup.sh
fi
module purge
module load {stack_name}
{SENTINEL_END}"""

def _build_base_bashrc_block() -> str:
    """Reset block — just loads the base spack module path, no specific stack."""
    return f"""{SENTINEL_START}
# Source Spack/Lmod setup for non-interactive shells (like Slurm jobs)
if [ -f /etc/profile.d/spack_setup.sh ]; then
    source /etc/profile.d/spack_setup.sh
fi
# No environment profile assigned — using base Spack module path
if [ -d /export/apps/spack ]; then
    module use /export/apps/spack/share/spack/lmod/linux-almalinux9-x86_64/Core
fi
{SENTINEL_END}"""

# ---------------------------------------------------------------------------
# Helper: SSH utilities
# ---------------------------------------------------------------------------

async def _ssh_run(commands: list) -> list:
    executor = SSHExecutor(
        host=settings.MASTER_IP,
        username=settings.MASTER_USER,
        password=settings.MASTER_PASS,
    )
    results = []
    for cmd in commands:
        out = []
        async for line in executor.run_command_stream(cmd):
            out.append(line)
        results.append("\n".join(out))
    return results


async def _write_lua_file(stack: EnvStack):
    """Write the Lua metamodule file to the master node's custom_modules dir."""
    lua_content = _build_lua_content(stack)
    # Escape single-quotes for bash heredoc safety
    escaped = lua_content.replace("'", "'\\''")
    cmd = (
        "mkdir -p /export/apps/custom_modules && "
        f"cat > /export/apps/custom_modules/{stack.name}.lua << 'LUAEOF'\n{lua_content}\nLUAEOF"
    )
    # Also ensure the custom_modules dir is in MODULEPATH via spack_setup.sh (idempotent)
    ensure_cmd = (
        "grep -qxF 'module use /export/apps/custom_modules' /var/lib/warewulf/overlays/nodeconfig/etc/profile.d/spack_setup.sh "
        "|| echo 'module use /export/apps/custom_modules' >> /var/lib/warewulf/overlays/nodeconfig/etc/profile.d/spack_setup.sh; "
        "grep -qxF 'module use /export/apps/custom_modules' /etc/profile.d/spack_setup.sh "
        "|| echo 'module use /export/apps/custom_modules' >> /etc/profile.d/spack_setup.sh"
    )
    await _ssh_run([cmd, ensure_cmd])


async def _delete_lua_file(stack_name: str):
    cmd = f"rm -f /export/apps/custom_modules/{stack_name}.lua"
    await _ssh_run([cmd])


async def _inject_bashrc(username: str, block: str):
    """Remove old managed block from ~/.bashrc and append new one."""
    # Python one-liner to strip old block and append new one
    remove_cmd = (
        f"python3 -c \""
        f"import re, pathlib; "
        f"p = pathlib.Path('/home/{username}/.bashrc'); "
        f"content = p.read_text() if p.exists() else ''; "
        f"cleaned = re.sub(r'\\n?# --- HPC PROFILE MANAGED BLOCK START ---.*?# --- HPC PROFILE MANAGED BLOCK END ---\\n?', '', content, flags=re.DOTALL); "
        f"p.write_text(cleaned)\""
    )
    append_cmd = f"printf '\\n{block}\\n' >> /home/{username}/.bashrc"
    await _ssh_run([remove_cmd, append_cmd])

# ---------------------------------------------------------------------------
# Startup seeder helper (called from main.py on startup)
# ---------------------------------------------------------------------------

async def seed_default_stacks(db: AsyncSession):
    """Insert or update default stacks, and cleanup old deprecated ones."""
    default_names = [s["name"] for s in DEFAULT_STACKS]
    
    # 1. Update or Insert current default stacks
    for s in DEFAULT_STACKS:
        result = await db.execute(select(EnvStack).where(EnvStack.name == s["name"]))
        existing = result.scalars().first()
        if existing:
            existing.display_name = s["display_name"]
            existing.description = s["description"]
            existing.category = s["category"]
            existing.modules = s["modules"]
        else:
            db.add(EnvStack(**s))
            
    # 2. Cleanup deprecated default stacks
    deprecated_names = ["python-scientific", "mpi-parallel"]
    for dep_name in deprecated_names:
        if dep_name not in default_names:
            result = await db.execute(select(EnvStack).where(EnvStack.name == dep_name))
            dep = result.scalars().first()
            if dep:
                await db.delete(dep)
                
    await db.commit()

    # 3. Write/Regenerate Lua files for all seeded stacks
    for s in DEFAULT_STACKS:
        result = await db.execute(select(EnvStack).where(EnvStack.name == s["name"]))
        stack = result.scalars().first()
        if stack:
            try:
                await _write_lua_file(stack)
            except Exception as e:
                print(f"[WARN] Failed to write Lua file for seeded stack {stack.name}: {e}")


# ---------------------------------------------------------------------------
# ADMIN ROUTES
# ---------------------------------------------------------------------------

@router.get("/", response_model=List[EnvStackResponse])
async def list_stacks(db: AsyncSession = Depends(get_db)):
    """List all environment stacks. Public — all authenticated users can read."""
    result = await db.execute(select(EnvStack).order_by(EnvStack.id))
    stacks = result.scalars().all()
    return [
        EnvStackResponse(
            id=s.id,
            name=s.name,
            display_name=s.display_name,
            description=s.description,
            category=s.category,
            modules=[m.strip() for m in s.modules.split(",") if m.strip()],
            created_at=s.created_at,
        )
        for s in stacks
    ]


@router.post("/", response_model=EnvStackResponse)
async def create_stack(
    stack_in: EnvStackCreate,
    current_user: TokenUser = Depends(get_admin_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(EnvStack).where(EnvStack.name == stack_in.name))
    if result.scalars().first():
        raise HTTPException(status_code=400, detail=f"Stack '{stack_in.name}' already exists.")

    new_stack = EnvStack(
        name=stack_in.name,
        display_name=stack_in.display_name,
        description=stack_in.description or "",
        category=stack_in.category,
        modules=",".join(stack_in.modules),
    )
    db.add(new_stack)
    await db.commit()
    await db.refresh(new_stack)

    # Write Lua file on master node
    try:
        await _write_lua_file(new_stack)
    except Exception as e:
        # Log but don't fail — file can be retried
        print(f"[WARN] Could not write .lua file for {new_stack.name}: {e}")

    return EnvStackResponse(
        id=new_stack.id,
        name=new_stack.name,
        display_name=new_stack.display_name,
        description=new_stack.description,
        category=new_stack.category,
        modules=stack_in.modules,
        created_at=new_stack.created_at,
    )


@router.put("/{stack_id}", response_model=EnvStackResponse)
async def update_stack(
    stack_id: int,
    stack_in: EnvStackUpdate,
    current_user: TokenUser = Depends(get_admin_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(EnvStack).where(EnvStack.id == stack_id))
    stack = result.scalars().first()
    if not stack:
        raise HTTPException(status_code=404, detail="Stack not found")

    if stack_in.display_name is not None:
        stack.display_name = stack_in.display_name
    if stack_in.description is not None:
        stack.description = stack_in.description
    if stack_in.category is not None:
        stack.category = stack_in.category
    if stack_in.modules is not None:
        stack.modules = ",".join(stack_in.modules)

    await db.commit()
    await db.refresh(stack)

    try:
        await _write_lua_file(stack)
    except Exception as e:
        print(f"[WARN] Could not regenerate .lua file for {stack.name}: {e}")

    return EnvStackResponse(
        id=stack.id,
        name=stack.name,
        display_name=stack.display_name,
        description=stack.description,
        category=stack.category,
        modules=[m.strip() for m in stack.modules.split(",") if m.strip()],
        created_at=stack.created_at,
    )


@router.delete("/{stack_id}")
async def delete_stack(
    stack_id: int,
    current_user: TokenUser = Depends(get_admin_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(EnvStack).where(EnvStack.id == stack_id))
    stack = result.scalars().first()
    if not stack:
        raise HTTPException(status_code=404, detail="Stack not found")

    stack_name = stack.name
    await db.delete(stack)
    await db.commit()

    try:
        await _delete_lua_file(stack_name)
    except Exception as e:
        print(f"[WARN] Could not delete .lua file for {stack_name}: {e}")

    return {"message": f"Stack '{stack_name}' deleted."}


@router.post("/{stack_id}/assign/{username}")
async def assign_stack_to_user(
    stack_id: int,
    username: str,
    current_user: TokenUser = Depends(get_admin_user),
    db: AsyncSession = Depends(get_db),
):
    """Admin assigns an environment profile to a specific user."""
    result = await db.execute(select(EnvStack).where(EnvStack.id == stack_id))
    stack = result.scalars().first()
    if not stack:
        raise HTTPException(status_code=404, detail="Stack not found")

    user_result = await db.execute(select(User).where(User.username == username))
    user = user_result.scalars().first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    user.env_profile = stack.name
    await db.commit()

    try:
        await _inject_bashrc(username, _build_bashrc_block(stack.name))
    except Exception as e:
        print(f"[WARN] Could not inject bashrc for {username}: {e}")

    return {"message": f"Profile '{stack.display_name}' assigned to '{username}'."}


@router.delete("/assign/{username}")
async def unassign_stack_from_user(
    username: str,
    current_user: TokenUser = Depends(get_admin_user),
    db: AsyncSession = Depends(get_db),
):
    """Admin resets a user's profile back to base Spack."""
    user_result = await db.execute(select(User).where(User.username == username))
    user = user_result.scalars().first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    user.env_profile = None
    await db.commit()

    try:
        await _inject_bashrc(username, _build_base_bashrc_block())
    except Exception as e:
        print(f"[WARN] Could not reset bashrc for {username}: {e}")

    return {"message": f"Profile reset to base Spack for '{username}'."}


# ---------------------------------------------------------------------------
# USER SELF-SERVICE ROUTES
# ---------------------------------------------------------------------------

@router.get("/modules", response_model=list[str])
async def get_available_modules(
    current_user: TokenUser = Depends(get_current_user),
):
    """
    Dynamically fetch all available Spack and custom Lmod modules from the master node.
    Requires admin or regular user access (any authenticated user can view modules).
    """
    cmd = "source /etc/profile.d/spack_setup.sh && module -t avail 2>&1"
    try:
        results = await _ssh_run([cmd])
        if not results or not results[0]:
            return []
            
        modules = set()
        for line in results[0].splitlines():
            line = line.strip()
            # Ignore empty lines, directory paths (ending in :), and general category names (ending in /)
            if not line or line.endswith(":") or line.endswith("/"):
                continue
            modules.add(line)
            
        return sorted(list(modules))
    except Exception as e:
        print(f"[ERROR] Failed to fetch available modules: {e}")
        return []

@router.get("/me", response_model=dict)
async def get_my_profile(
    current_user: TokenUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get the current user's assigned profile and available stacks."""
    all_stacks_result = await db.execute(select(EnvStack).order_by(EnvStack.id))
    all_stacks = all_stacks_result.scalars().all()

    return {
        "username": current_user.username,
        "env_profile": current_user.env_profile,
        "available_stacks": [
            {
                "id": s.id,
                "name": s.name,
                "display_name": s.display_name,
                "description": s.description,
                "category": s.category,
                "modules": [m.strip() for m in s.modules.split(",") if m.strip()],
            }
            for s in all_stacks
        ],
    }


@router.post("/me/select")
async def user_select_profile(
    body: UserEnvProfileUpdate,
    current_user: TokenUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """User selects (or clears) their own environment profile."""
    if body.stack_name == "" or body.stack_name == "none":
        current_user.env_profile = None
        await db.commit()
        try:
            await _inject_bashrc(current_user.username, _build_base_bashrc_block())
        except Exception as e:
            print(f"[WARN] Could not reset bashrc for {current_user.username}: {e}")
        return {"message": "Profile reset to base Spack environment."}

    # Verify stack exists
    result = await db.execute(select(EnvStack).where(EnvStack.name == body.stack_name))
    stack = result.scalars().first()
    if not stack:
        raise HTTPException(status_code=404, detail=f"Stack '{body.stack_name}' not found")

    current_user.env_profile = stack.name
    await db.commit()

    try:
        await _inject_bashrc(current_user.username, _build_bashrc_block(stack.name))
    except Exception as e:
        print(f"[WARN] Could not inject bashrc for {current_user.username}: {e}")

    return {"message": f"Profile switched to '{stack.display_name}'. It will load on your next login."}


@router.post("/me/save-collection")
async def user_save_lmod_collection(
    body: dict,
    current_user: TokenUser = Depends(get_current_user),
):
    """
    Triggers 'module save <collection_name>' on the master node for the current user.
    This lets users save a named Lmod Collection from their current loaded modules.
    """
    collection_name = body.get("collection_name", "my_env")
    if not collection_name or not collection_name.replace("-", "").replace("_", "").isalnum():
        raise HTTPException(status_code=400, detail="Invalid collection name. Use only letters, numbers, hyphens, underscores.")

    # Run as the actual user via sudo -u
    cmd = f"sudo -u {current_user.username} bash -c 'source /etc/profile.d/spack_setup.sh && module save {collection_name}'"
    try:
        await _ssh_run([cmd])
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return {"message": f"Lmod collection '{collection_name}' saved for user '{current_user.username}'."}


@router.get("/me/collections")
async def user_list_lmod_collections(
    current_user: TokenUser = Depends(get_current_user),
):
    """List saved Lmod collections for the current user."""
    cmd = f"sudo -u {current_user.username} bash -c 'source /etc/profile.d/spack_setup.sh && module savelist 2>&1'"
    results = []
    try:
        results = await _ssh_run([cmd])
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return {"collections": results[0] if results else ""}


@router.post("/me/restore-collection")
async def user_restore_lmod_collection(
    body: dict,
    current_user: TokenUser = Depends(get_current_user),
):
    """Restore a saved Lmod collection for the current user by injecting it into .bashrc."""
    collection_name = body.get("collection_name", "")
    if not collection_name:
        raise HTTPException(status_code=400, detail="collection_name is required")

    block = f"""{SENTINEL_START}
# Source Spack/Lmod setup for non-interactive shells (like Slurm jobs)
if [ -f /etc/profile.d/spack_setup.sh ]; then
    source /etc/profile.d/spack_setup.sh
fi
module restore {collection_name}
{SENTINEL_END}"""

    try:
        await _inject_bashrc(current_user.username, block)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return {"message": f"Collection '{collection_name}' set as default login environment."}
